
const Nosotros = () => {
  return (
    <div className="nosotros bg-white/90 flex flex-col items-center p-4 md:p-12 mt-2">
      <h3 className="text-2xl md:text-4xl font-bold font-anton tracking-[4px] mb-1 md:mb-3">MISIÓN</h3>
      <p className="mb-3 md:mb-7 font-ubuntu text-left md:text-justify md:text-md text-sm">U.A.M. ES UN SISTEMA ORGANIZATIVO QUE REPRESENTA AL SECTOR MINIFUNDISTA PARA PROMOVER EL DESARROLLO INTEGRAL DE SUS ASOCIADOS, FACILITANDO LA FORMACIÓN E IMPLEMENTACIÓN DE PROCESOS EN AGROECOLOGÍA, ECONOMÍA SOLIDARIA, SOBERANÍA ALIMENTARIA, EQUIDAD DE GÉNERO, LIDERAZGO Y FINANCIAMIENTO DE CAPITAL, A TRAVÉS DE PROGRAMAS Y PROYECTOS.</p>
      <h3 className="text-2xl md:text-4xl font-bold font-anton tracking-[4px] mb-1 md:mb-3">VISIÓN</h3>
      <p className="mb-3 md:mb-7 font-ubuntu text-left md:text-justify md:text-md text-sm">DESARROLLAR PROCESOS ESTRATÉGICOS PARA LA SOSTENIBILIDAD, CONSOLIDACIÓN TÉCNICA, ADMINISTRATIVA Y AGROECOLOGÍA, LO QUE HACE UN MODELO EJEMPLAR, REPLICABLE, EN ORGANIZACIONES SOCIALES. SE TIENE ALTA CALIDAD EN LA PRODUCCIÓN Y COMERCIALIZACIÓN DE LOS PRODUCTOS EN EL ÁMBITO LOCAL E INTERNACIONAL, CON LA PARTICIPACIÓN DE HOMBRES Y MUJERES, COMPROMETIDA EN LA CONSERVACIÓN Y PROTECCIÓN DEL MEDIO AMBIENTE, CON POSICIONAMIENTO EN DEFENSA DE LA SOBERANÍA ALIMENTARIA. CUENTA CON UN GRUPO HUMANO Y PROFESIONAL COMPETENTE QUE TRABAJA COORDINADAMENTE PARA MEJORAR Y MANTENER SUS PROCESOS DE DESARROLLO.</p>
    </div> 
  )
}

export default Nosotros