import Head from 'next/head';
import '@styles/tailwind.css';
import Header from '@containers/Header';
import { useEffect, useState } from 'react'
import Footer from '@containers/Footer';


function MyApp({ Component, pageProps }) {
  const [ title, setTitle ] = useState(" Unión de Agricultores Minifundistas de Guatemala -U.A.M.-    ")

  // useEffect(()=>{
  //   const espera= 600;
  //   const interval = setInterval(()=> {
  //     title = title.substring(1,title.length)+title.charAt(0);
  //     setTitle(title);
  //   }, espera);

  //   return ()=> clearInterval(interval);
  //  });

  return(
  <> 
    <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/ICUAM.ico" />
        <meta name="description" content="" />
        <meta name="keywords" content="agroecología" />
        <meta name="author" content="Unión de Agricultores" />
        <meta name="copyright" content="" />
        <meta name="robots" content="index" />
        <meta name="robots" content="follow"/>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin='true' />
    </Head>
    <div 
      className='container max-w-none m-0 bg-[url("../assets/images/background-camp.jpg")] bg-fixed bg-[length:170%_100%] lg:bg-[length:100%_100%] overflow-auto flex flex-col items-center gap-2' 
       >
      <Header />
      <main className='w-11/12 min-w-none'>
        <Component {...pageProps} />
      </main>
      <Footer />  
    </div>
  </>
  );
};

export default MyApp;
