import Head from 'next/head';
import '@styles/tailwind.css';
import Header from '@containers/Header';

function MyApp({ Component, pageProps }) {
  return(
  <> 
    <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/ICUAM.ico" />
        <meta name="description" content="" />
        <meta name="keywords" content="agroecología" />
        <meta name="author" content="Unión de Agricultores" />
        <meta name="copyright" content="" />
        <meta name="robots" content="index" />
        <meta name="robots" content="follow"/>
    </Head>
    <Header />
    <Component {...pageProps} />
  </>
  );
};

export default MyApp;
